// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgf6WV9m5ewIfvCMWJYLNeX6g3BZnZsg',
    appId: '1:875082229669:web:5b17a426ce0a17bf5d2a4c',
    messagingSenderId: '875082229669',
    projectId: 'finance-book-dc9ca',
    authDomain: 'finance-book-dc9ca.firebaseapp.com',
    storageBucket: 'finance-book-dc9ca.firebasestorage.app',
    measurementId: 'G-QT8QDPF3M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQdf_wBnCZWBcIDxkygb-XFxpoaKczEzk',
    appId: '1:875082229669:android:8088d728e53ca9245d2a4c',
    messagingSenderId: '875082229669',
    projectId: 'finance-book-dc9ca',
    storageBucket: 'finance-book-dc9ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2sVhbr1-tJ-5ihHAqgaZflqIuJtOaUA',
    appId: '1:875082229669:ios:8b60577a00c6d2ec5d2a4c',
    messagingSenderId: '875082229669',
    projectId: 'finance-book-dc9ca',
    storageBucket: 'finance-book-dc9ca.firebasestorage.app',
    androidClientId:
        '875082229669-hknnd5ndqunmruluji1b7vukkho2lu9b.apps.googleusercontent.com',
    iosClientId:
        '875082229669-4j6i5jj069fualvon3580a8pgvjmksml.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinanceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH2sVhbr1-tJ-5ihHAqgaZflqIuJtOaUA',
    appId: '1:875082229669:ios:8b60577a00c6d2ec5d2a4c',
    messagingSenderId: '875082229669',
    projectId: 'finance-book-dc9ca',
    storageBucket: 'finance-book-dc9ca.firebasestorage.app',
    androidClientId:
        '875082229669-hknnd5ndqunmruluji1b7vukkho2lu9b.apps.googleusercontent.com',
    iosClientId:
        '875082229669-4j6i5jj069fualvon3580a8pgvjmksml.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinanceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlgf6WV9m5ewIfvCMWJYLNeX6g3BZnZsg',
    appId: '1:875082229669:web:5b17a426ce0a17bf5d2a4c',
    messagingSenderId: '875082229669',
    projectId: 'finance-book-dc9ca',
    authDomain: 'finance-book-dc9ca.firebaseapp.com',
    storageBucket: 'finance-book-dc9ca.firebasestorage.app',
    measurementId: 'G-QT8QDPF3M5',
  );
}
